/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.controleFinanceiro.view;

import com.controleFinanceiro.model.Usuario;
import com.controleFinanceiro.DAO.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();

        
        setSize(837,590);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLogin = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        btmLogin = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        papelLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(0, 0, 0));
        txtLogin.setText("Insira seu email:");
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        campoUsuario.setBackground(new java.awt.Color(17, 17, 160));
        campoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        campoUsuario.setBorder(null);
        campoUsuario.addActionListener(this::campoUsuarioActionPerformed);
        getContentPane().add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 308, 342, 42));

        txtSenha.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(0, 0, 0));
        txtSenha.setText("Insira sua senha:");
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 355, -1, -1));

        campoSenha.setBackground(new java.awt.Color(17, 17, 160));
        campoSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoSenha.setForeground(new java.awt.Color(255, 255, 255));
        campoSenha.setBorder(null);
        getContentPane().add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 378, 342, 42));

        btmLogin.setForeground(new java.awt.Color(0, 0, 0));
        btmLogin.setText("LOGIN");
        btmLogin.setBorder(null);
        btmLogin.setBorderPainted(false);
        btmLogin.setContentAreaFilled(false);
        btmLogin.setFocusPainted(false);
        btmLogin.addActionListener(this::btmLoginActionPerformed);
        getContentPane().add(btmLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 160, 40));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel1.setText("Bem-Vindo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 210, -1));

        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Lembrar senha");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 160, -1));

        papelLogin.setForeground(new java.awt.Color(0, 0, 0));
        papelLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatGPT Image 20 de mai. de 2026, 17_40_53.png"))); // NOI18N
        getContentPane().add(papelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 840, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmLoginActionPerformed
        // TODO add your handling code here:

        String email = campoUsuario.getText();
        String senha = new String(campoSenha.getPassword());

        if (email.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Preencha o email ou senha","Atenção",JOptionPane.WARNING_MESSAGE);
            return;
        }

        UsuarioDAO dao = new UsuarioDAO();
        Usuario usuario = dao.Login(email,senha);

        if (usuario != null) {
            JOptionPane.showMessageDialog(this,
                    "Bem-vindo, " + usuario.getNome() + "!");
            new dashBoardPrincipal().setVisible(true); // abre a tela principal
            this.dispose(); // fecha a tela de login
        } else {
            JOptionPane.showMessageDialog(this,
                    "Email ou senha incorretos!",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }

       
    }//GEN-LAST:event_btmLoginActionPerformed

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btmLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel papelLogin;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtSenha;
    // End of variables declaration//GEN-END:variables
}
